-- MySQL Script generated by MySQL Workbench
-- Fri Aug 19 16:50:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blog-ccva
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blog-ccva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog-ccva` DEFAULT CHARACTER SET utf8 ;
USE `blog-ccva` ;

-- -----------------------------------------------------
-- Table `blog-ccva`.`user-`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog-ccva`.`user-` (
  `Nombre` VARCHAR(25) NOT NULL,
  `Apellido` VARCHAR(25) NOT NULL,
  `DNI` CHAR(8) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NULL,
  `domicilio` VARCHAR(45) NOT NULL,
  `telefono` CHAR(10) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `role` INT NOT NULL,
  `Fecha de nacimiento` DATETIME NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`DNI`),
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog-ccva`.`template 4`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog-ccva`.`template 4` (
  ``  NOT NULL,
  PRIMARY KEY (``));


-- -----------------------------------------------------
-- Table `blog-ccva`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog-ccva`.`categoria` (
  `id_post` INT NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `hora` DATE NOT NULL,
  `dia` DATE NOT NULL,
  `año` DATE NOT NULL,
  `user_DNI` CHAR(8) NOT NULL,
  PRIMARY KEY (`id_post`, `user_DNI`),
  INDEX `fk_post_user_idx` (`user_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_post_user00`
    FOREIGN KEY (`user_DNI`)
    REFERENCES `blog-ccva`.`user-` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog-ccva`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog-ccva`.`post` (
  `id_post` INT NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `hora` DATE NOT NULL,
  `dia` DATE NOT NULL,
  `año` DATE NOT NULL,
  `user_DNI` CHAR(8) NOT NULL,
  `categoria_id_post` INT NOT NULL,
  `categoria_user_DNI` CHAR(8) NOT NULL,
  PRIMARY KEY (`id_post`, `user_DNI`, `categoria_id_post`, `categoria_user_DNI`),
  INDEX `fk_post_user_idx` (`user_DNI` ASC) VISIBLE,
  INDEX `fk_post_categoria1_idx` (`categoria_id_post` ASC, `categoria_user_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_post_user`
    FOREIGN KEY (`user_DNI`)
    REFERENCES `blog-ccva`.`user-` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_categoria1`
    FOREIGN KEY (`categoria_id_post` , `categoria_user_DNI`)
    REFERENCES `blog-ccva`.`categoria` (`id_post` , `user_DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog-ccva`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog-ccva`.`comentarios` (
  `id_post` INT NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `hora` DATE NOT NULL,
  `dia` DATE NOT NULL,
  `año` DATE NOT NULL,
  `user_DNI` CHAR(8) NOT NULL,
  `post_id_post` INT NOT NULL,
  `post_user_DNI` CHAR(8) NOT NULL,
  `post_categoria_id_post` INT NOT NULL,
  `post_categoria_user_DNI` CHAR(8) NOT NULL,
  PRIMARY KEY (`id_post`, `user_DNI`),
  INDEX `fk_post_user_idx` (`user_DNI` ASC) VISIBLE,
  INDEX `fk_comentarios_post1_idx` (`post_id_post` ASC, `post_user_DNI` ASC, `post_categoria_id_post` ASC, `post_categoria_user_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_post_user0`
    FOREIGN KEY (`user_DNI`)
    REFERENCES `blog-ccva`.`user-` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_post1`
    FOREIGN KEY (`post_id_post` , `post_user_DNI` , `post_categoria_id_post` , `post_categoria_user_DNI`)
    REFERENCES `blog-ccva`.`post` (`id_post` , `user_DNI` , `categoria_id_post` , `categoria_user_DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `blog-ccva` ;

-- -----------------------------------------------------
-- Placeholder table for view `blog-ccva`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog-ccva`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `blog-ccva`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog-ccva`.`view1`;
USE `blog-ccva`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
